=== raml-apis/BlockScore/schemas/historicalQuestionSetsResponse-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "total_count" : {
      "type" : "number" ,
      "required" : false
    } ,
    "has_more" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "object" : {
      "type" : "string" ,
      "required" : false
    } ,
    "data" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "object" : {
              "type" : "string" ,
              "required" : false
            } ,
            "id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "created_at" : {
              "type" : "number" ,
              "required" : false
            } ,
            "updated_at" : {
              "type" : "number" ,
              "required" : false
            } ,
            "livemode" : {
              "type" : "boolean" ,
              "required" : false
            } ,
            "person_id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "score" : {
              "type" : "number" ,
              "required" : false
            } ,
            "expired" : {
              "type" : "boolean" ,
              "required" : false
            } ,
            "time_limit" : {
              "type" : "number" ,
              "required" : false
            } ,
            "questions" : {
              "type" : "array" ,
              "required" : false ,
              "items" : [
                {
                  "type" : "object" ,
                  "properties" : {
                    "id" : {
                      "type" : "number" ,
                      "required" : false
                    } ,
                    "question" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "answers" : {
                      "type" : "array" ,
                      "required" : false ,
                      "items" : [
                        {
                          "type" : "object" ,
                          "properties" : {
                            "id" : {
                              "type" : "number" ,
                              "required" : false
                            } ,
                            "answer" : {
                              "type" : "string" ,
                              "required" : false
                            }
                          }
                        }
                      ]
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

=== raml-apis/BlockScore/examples/listAllCompaniesResponse-example.json
{
  "total_count" : 443 ,
  "has_more" : true ,
  "object" : "list" ,
  "data" : [
    {
      "object" : "company" ,
      "id" : "54d956c06230620003760500" ,
      "created_at" : 1423529664 ,
      "updated_at" : 1423529664 ,
      "status" : "valid" ,
      "livemode" : false ,
      "entity_name" : "BlockScore" ,
      "tax_id" : "123410000" ,
      "incorporation_day" : 23 ,
      "incorporation_month" : 8 ,
      "incorporation_year" : 1993 ,
      "incorporation_state" : "DE" ,
      "incorporation_country_code" : "US" ,
      "incorporation_type" : "corporation" ,
      "dbas" : "BitRemit" ,
      "registration_number" : "123123123" ,
      "email" : "test@example.com" ,
      "url" : "https://blockscore.com" ,
      "phone_number" : "6505555555" ,
      "note" : "ref-id:12345" ,
      "ip_address" : "67.160.8.182" ,
      "address_street1" : "123 Fake Streets" ,
      "address_street2" : null ,
      "address_city" : "Stanford" ,
      "address_subdivision" : "CA" ,
      "address_postal_code" : "94305" ,
      "address_country_code" : "US" ,
      "details" : {
        "ofac" : "no_match" ,
        "state" : "match" ,
        "tax_id" : "match" ,
        "address" : "no_match" ,
        "entity_name" : "mismatch" ,
        "incorp_date" : "no_match" ,
        "country_code" : "match"
      }
    }
  ]
}

=== raml-apis/BlockScore/examples/historicalQuestionSetsResponse-example.json
{
  "total_count": 5,
  "has_more": false,
  "object": "list",
  "data": [
    {
      "object": "question_set",
      "id": "533ce7e5627463792f010000",
      "created_at": 1402450269,
      "updated_at": 1403742375,
      "livemode": false,
      "person_id": "530c48b2627463452b570000",
      "score": 60.0,
      "expired": false,
      "time_limit": 300,
      "questions": [
        {
          "id": 1,
          "question": "Which of these people do you know?",
          "answers": [
            { "id": 1, "answer": "Alain" },
            { "id": 2, "answer": "John" },
            { "id": 3, "answer": "Chris" },
            { "id": 4, "answer": "Connor" },
            { "id": 5, "answer": "None Of The Above" }
          ]
        }
      ]
    }
  ]
}
